### ISSUE TITLE
Extension for VS2019

### ISSUE THREAD

**Issue by bacobart** [ykoksen/unused-task-warning#12]
Hi,

Do you plan on releasing a version for VS2019? Would really appreciate it :)

**Comment by samusaran** [comment]
I could look into it, since I still have some implementations in progress. Only @ykoksen can publish the nuget package tho.

**Comment by samusaran** [comment]
The vsix analyzer seems to work just fine in VS2019 without any changes, so we should only bump the target versions. I'll commit the change.

**Comment by ykoksen** [comment]
Looking into the pull request @samusaran made regarding this

**Comment by ykoksen** [comment]
I've uploaded a new vsix version supporting both 2017 and 2019
