### ISSUE TITLE
Please clarify which projects are analyzed when adding to some of the projects in a solution

### ISSUE THREAD

**Issue by miguelhughes** [ykoksen/unused-task-warning#23]
Hi! I'm having a hard time figuring out how to integrate it into my solution. So maybe this could just go in the readme section. This is related to a solution with multiple projects (23 in my case)
When I add the package to a project, any unused tasks in that project are warned immediately, which is great. If there is another project that references this project, unused tasks in that project are also found. However if I continue going upwards, the errors are no longer found. Example:

Domain (has nuget package)

Service (references Domain)

Web (references Service)

Errors are correctly found in Domain and in Service, but not on Web.

Could we get a clarification on how/where we should add the nuget package so that we're sure that all of our solution is analyzed?

**Comment by ykoksen** [comment]
Hi @miguelhughes 

I understand your need. I'm not sure the NuGet package is the correct location for how to use analyzers - this is part of the .Net or Visual Studio domain. Also I might be too much of an expert - I just installed the NuGet package to all the projects I want covered. This also seems to be in accordance with the documentation I've found:
https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019
Qoute:

> **Scope**
If you install analyzers as a Visual Studio extension, they apply at the solution level and to all instances of Visual Studio. If you install the analyzers as a NuGet package, which is the preferred method, they apply only to the project where the NuGet package was installed. In team environments, analyzers installed as NuGet packages are in scope for all developers that work on that project.

I will however most likely add a reference to the above documentation.

**Comment by miguelhughes** [comment]
Thanks for clarifying that. Would having the analyzer as a VS extension be basically the same as what the [already existing extension](https://marketplace.visualstudio.com/items?itemName=Lindhart.missingAwaitWarning) does, or does it require some other steps to install?

If I continue down the nuget package route, I just just add the package to my 23 projects?

**Comment by ykoksen** [comment]
I'm in doubt what you mean. the 

> analyzer as a VS extension

 is exactly the

> already existing extension

So I'm unable to answer your question. I can say that the only way of installing the analyzer is by using the link you provided and download it (or build it and install it - would be an identical installation file). I will recommend using the NuGet package though. The VS extension only works on files you have open in VS - the NuGet package works on all builds.
