### ISSUE TITLE
Can the Nuget be installed as development asset only?

### ISSUE THREAD

**Issue by radleta** [ykoksen/unused-task-warning#25]
First, great work on this Nuget. Love the warnings!

It appears when the Nuget package is installed it's installed as a true dependency to the project and not a development dependency.

Here is an example of another analyzer inclusion in the project. The AsyncFixer installs itself as `PrivateAssets` with `all` which prevents its dependencies and inclusion in the output of the project.
```
	  <PackageReference Include="AsyncFixer" Version="1.1.6">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
```

The Lindhart.Analyser.MissingAwaitWarning package installs itself into the project like the below.
And because of this, it causes the System.Threading.Tasks.Extensions to be added as a dependency to the project at v4.3.0. Also it includes the library in the output.
```
	  <PackageReference Include="Lindhart.Analyser.MissingAwaitWarning" Version="1.2.0" />
```

Is it possible to update the Nuget to be development only asset? Or is this behavior by design?

**Comment by samusaran** [comment]
I'm not actively following the project anymore, but I don't think there are any constraints in using `PrivateAssets`.

Oddly enough, I had a problem on a client project where the `System.Threading.Tasks.Extensions` library was added on the project by this analyzer, and because of some dependency hell the program wasn't starting anymore.

**Comment by ykoksen** [comment]
Looks rather easy. I can probably get around to it within a couple of days, maybe a week.

If you want it faster you are welcome to make the modification yourself and make a pull request for it :-)

**Comment by radleta** [comment]
@ykoksen thanks so much! That would be great. I don't mind attempting it. If you beat me to it, please don't wait on me for it though. My schedule is pretty crazy the next bit.

**Comment by ykoksen** [comment]
As you can see I've made a draft pull request on this (you are very welcome to have a look) - and I've made a beta version available on GitHub. Any feedback is much appreciated.
