### ISSUE TITLE
ValueTask gives no warning

### ISSUE THREAD

**Issue by jorisvergeer** [ykoksen/unused-task-warning#30]
Hi,

I am working on some code that uses IAsyncDisposable. This returns an ValueTask (without type argument). 

In the code of your analyzer has those explicitly commented out because those types do not exist in .netstandard1.3. Point is that your analyzer does not need the types at all as you only do string comparison on the full names of the types.

I created a pull request where the type list is stored as string. I use this fixed version at the moment and it works great.

https://github.com/ykoksen/unused-task-warning/pull/29

Many thanks for this analyzer, it is helping me greatly at the moment.

**Comment by ykoksen** [comment]
The changes have been included in the 2.0.0-beta which have just been released
