### ISSUE TITLE
Analyzer doesn't detect missing awaits in null-conditional expressions

### ISSUE THREAD

**Issue by fszewczy** [ykoksen/unused-task-warning#34]
Hi,

Thanks for sharing this tool, it's very helpful.

Currently, this analyzer doesn't support null-conditional. 
Example:
`xxx?.DoSomethingAsync();`
Should give a warning when not awaited.

Are you planning to add support for this expression in future versions?

**Comment by ykoksen** [comment]
Hi,

Thanks for the feedback.

Well - I am now :-)

I believe that would be rather easy to fix, I'll take a look once I get time. There might be a chance soon due to Covid-19 lockdown.

**Comment by fszewczy** [comment]
Thanks for the reply. I'm glad you are considering adding this feature.

In the meantime I prototyped a solution by myself in https://github.com/fszewczy/unused-task-warning/tree/NullConditionalsSupport-wip.
Is that OK with you? If not, please let me know, I'm quite new to GitHub culture.

**Comment by ykoksen** [comment]
That's excellent. Make a pull request for it, then I'll look more into it.

Do you want to be a contributor to this project? Because then I'll just add you.

**Comment by fszewczy** [comment]
OK, I'll fix formatting and then make PR. If you find my code useful, I will gladly become a contributor of this project.
