### ISSUE TITLE
Configure via editorconfig

### ISSUE THREAD

**Issue by lonix1** [ykoksen/unused-task-warning#37]
Firstly, thanks for making this library... it really helped me clean up my code! :smiley:

With other analyser rules I can control them in `.editorconfig` like this:
````ini
dotnet_diagnostic.CA1012.severity = warning
````

How do I do that for this analyser rule? What is its code?

**Comment by lonix1** [comment]
Ok, I figured it out:
````ini
dotnet_diagnostic.LindhartAnalyserMissingAwaitWarning.severity = warning
````

I assume the default is `warning`? It can be changed to `error`, `warning`, `suggestion`, `silent`, `none`, `default`.

...thanks @ykoksen!

**Comment by ykoksen** [comment]
Hi

Sorry I'm not responding faster. Yes, there are two different rules. I plan to extract it into several rules with better description.
The most GUI user friendly way to change the severity directly in Visual Studio by expanding the Analyser under references:
https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022#set-rule-severity-from-solution-explorer

**Comment by lonix1** [comment]
> there are two different rules.

I only knew of `dotnet_diagnostic.LindhartAnalyserMissingAwaitWarning` - which is the other one?

> in Visual Studio by expanding the Analyser under references

I'm using vscode so I don't see that, but I don't mind using editorconfig though I find it easier.

**Comment by howlettt** [comment]
`dotnet_diagnostic.LindhartAnalyserMissingAwaitWarningStrict` is the other one for anyone else stumbling across this
