### ISSUE TITLE
VS 2022 support

### ISSUE THREAD

**Issue by drauch** [ykoksen/unused-task-warning#38]
Please support VS 2022, thank you :-)

**Comment by ykoksen** [comment]
Hi, the Visual Studio extension is no longer being updated. I recommend using the NuGet analyser instead.

**Comment by drauch** [comment]
Which NuGet analyzer are you talking about?

**Comment by 304NotModified** [comment]
> Which NuGet analyzer are you talking about?

This one: 
https://www.nuget.org/packages/Lindhart.Analyser.MissingAwaitWarning/

See the readme
