### ISSUE TITLE
Analyzer is unable to detect never awaited tasks which are asigned to a variable

### ISSUE THREAD

**Issue by suchoss** [ykoksen/unused-task-warning#44]
I expected that the it would be able to find Task assigned to variable but still never awaited.
![image](https://user-images.githubusercontent.com/39336141/181730986-a19755e7-c1cf-491a-a3a3-49329afc2bfc.png)

[You can test it on this project](https://github.com/suchoss/AsyncTaskAnalyzer/blob/master/AsyncTaskAnalyzerTest/Test.cs)

So far no analyzer was able to detect this problem. I would gladly help, but unfortunately I would need some "write your analyzer for dummies" manual.

**Comment by samusaran** [comment]
If you enable the “strict” policy, the analyzer will detect those issues.

I really don’t remember how to do it tho, last time i used it was 4 years ago.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: 29 July 2022 11:38
To: ***@***.***>
Cc: ***@***.***>
Subject: [ykoksen/unused-task-warning] Analyzer is unable to detect never awaited tasks which are asigned to a variable (Issue #44)


I expected that the it would be able to find Task assigned to variable but still never awaited.
[image]<https://user-images.githubusercontent.com/39336141/181730986-a19755e7-c1cf-491a-a3a3-49329afc2bfc.png>

You can test it on this project<https://github.com/suchoss/AsyncTaskAnalyzer/blob/master/AsyncTaskAnalyzerTest/Test.cs>

So far no analyzer was able to detect this problem. I would gladly help, but unfortunately I would need some "write your analyzer for dummies" manual.

**Comment by suchoss** [comment]
I wonder If I do everything correctly?

I just installed nuget packed `<PackageReference Include="Lindhart.Analyser.MissingAwaitWarning" Version="2.0.0" />`

I built a project and received following warnings:
![image](https://user-images.githubusercontent.com/39336141/181738324-6c81de35-9033-4242-81de-9f6dbb0ad84a.png)

But to be honest I do not know where to find a "switch" for the "strict" policy.

**Comment by Yggdrasills** [comment]
Hello. I also encountered this problem and did not find a way to determine the end call. The task can be passed along the chain to methods, constructors, etc. endlessly, while handling different situations along the way (e.g. recursion). As a result, it will not be clear where to show the error. Therefore, this will create a load in the search through the search tree and will slow down the IDE

**Comment by suchoss** [comment]
@Yggdrasills I understand that this is no simple problem. On the other hand - I do not look for something that is 100 % exact and precise (like scalpel in surgeon's hand 🤔 - at least I hope they are that precise).

I just need something that can solve 90 % of my issues within a split second. Which is - search for this issue only within a method's scope. If the task is passed elsewhere, just do not track it (or maybe track it in simple cases). 

If I compare this solution with my current state (one regular expression, a pair of hands and set of eyes), this would be a rocket improvement 😄

**Comment by Yggdrasills** [comment]
@suchoss, For such a solution, you can recursively take the parent of the desired node (task) until you reach the entire method and analyze each line. Try look here https://github.com/Yggdrasills/UniTaskAnalyzer

**Comment by suchoss** [comment]
@Yggdrasills Currently I am blank sheet regarding Roslyn Analyzers. I do not know how to write one. Never worked with it. Could you point me, please, to some kind of easy step by step tutorial? 

(I will hope my head won't explode. I am feeling my brain is throwing a lot of `new OutOfMemoryException();`)

**Comment by Yggdrasills** [comment]
@suchoss, here is an [amazing tutorial](https://www.meziantou.net/writing-a-roslyn-analyzer.htm). Also If it doesn't help, you can ask me concrete questions

**Comment by suchoss** [comment]
@Yggdrasills I spent about 8 hours on this, I am at least able to create (it is more copy than create) custom analyzer. I tried to get inspiration [here](https://github.com/ykoksen/unused-task-warning/blob/master/Lindhart.Analyser.MissingAwaitWarning/Lindhart.Analyser.MissingAwaitWarning/Lindhart.Analyser.MissingAwaitWarning/LindhartAnalyserMissingAwaitWarningAnalyzer.cs) and [here](https://github.com/cezarypiatek/CSharpExtensions/blob/master/src/CSharpExtensions.Analyzers/ReturnValueUnusedAnalyzer.cs)

But what I do not know is
a) How do I find Method call which returns `Task` or `Task<object>` and is not awaited (this `Task` is assigned to a variable)?
b) How do I track usage of this variable within its scope?

I am kind of overwhelmed by number of properties in following code. And I do not understand where to search for what...
```
private void AnalyseSymbolNode( SyntaxNodeAnalysisContext context )
        {
            if (context.Node is ExpressionSyntax expression)
            {
                if (expression.Parent is ExpressionStatementSyntax && context.SemanticModel.GetTypeInfo(expression).Type is { } type && type.SpecialType != SpecialType.System_Void)
                {
                    var fullName = type.ToDisplayString();
                    
                    if (IsAsyncResult(type) || type.AllInterfaces.Any(IsAsyncResult))
                    {
                        var asyncResultDiagnostic = Diagnostic.Create(Rule, expression.GetLocation());
                        context.ReportDiagnostic(asyncResultDiagnostic);

                    }
                    
                }
            }
            
        }
        
        private static bool IsAsyncResult(ITypeSymbol x) => x.Name is "IAsyncResult";
```

**Comment by suchoss** [comment]
Fortunately Cezary Piątek extended [his repo](https://github.com/cezarypiatek/CSharpExtensions/issues/62) over the weekend. Can't say I completely understand what he is doing in his analyzer. But it works exactly as I needed. 

Still thanks for help.

**Comment by ykoksen** [comment]
Just wanted to add how to use the "Strict" rule:
In Visual Studio Solution Explorer, you can fold out the Analyzer to see the individual rules:
![image](https://user-images.githubusercontent.com/29013502/183497308-23db91d9-eb77-4b72-8369-2b155ba80dcc.png)

Then you can right click a rule to choose severity:
![image](https://user-images.githubusercontent.com/29013502/183497639-4e12ce39-5733-41a2-9657-e531b9ccba2c.png)

**Comment by suchoss** [comment]
Thanks.
